const BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;

export const UPLOAD_API = `${BASE_URL}/uploads`;
export const ACCOUNT_API = `${BASE_URL}/accounts`;
export const VERIFICATION_API = `${BASE_URL}/verification`;
export const AUTH_API = `${BASE_URL}/auth`;
export const BOOKING_API = `${BASE_URL}/bookings`;
export const CABIN_TYPES_API = `${BASE_URL}/cabin-types`;
export const CSV_API = `${BASE_URL}/csv`;
export const DISBURSEMENT_API = `${BASE_URL}/disbursement`;
export const EMAIL_API = `${BASE_URL}/email`;
export const NOTIFICATION_API = `${BASE_URL}/notifications`;
export const PASSENGER_API = `${BASE_URL}/passengers`;
export const PAYMENT_API = `${BASE_URL}/pay`;
export const PORTS_API = `${BASE_URL}/ports`;
export const REPORTING_API = `${BASE_URL}/reporting`;
export const SEARCH_API = `${BASE_URL}/search`;
export const SHIPPING_LINE_API = `${BASE_URL}/shipping-lines`;
export const SHIPS_API = `${BASE_URL}/ships`;
export const TRIP_API = `${BASE_URL}/trips`;
export const VEHICLE_TYPES_API = `${BASE_URL}/vehicle-types`;
export const VOUCHERS_API = `${BASE_URL}/vouchers`;
export const WEBHOOKS_API = `${BASE_URL}/webhooks`;
export const RATE_TABLES_API = `${BASE_URL}/rate-tables`;
export const RATE_TABLE_ROWS_API = `${BASE_URL}/rate-table-rows`;
export const SEAT_PLAN_API = `${BASE_URL}/seat-plans`;
export const THUMBNAIL_API = `${BASE_URL}/thumbnails`;
export const HEADER_SECTION_API = `${BASE_URL}/pages/header-config`;
export const HERO_SECTION_API = `${BASE_URL}/pages/home/page-sections/hero`;
export const FOOTER_SECTION_API = `${BASE_URL}/pages/footer-config`;
export const ABOUT_US_API = `${BASE_URL}/about-us`;
export const CONTACT_INFORMATION_API = `${BASE_URL}/contact-information`;
export const CONTACT_US_API = `${BASE_URL}/contact-us`; // Assumption for endpoint
export const THEME_SETTINGS_API = `${BASE_URL}/theme-settings`;
export const FAQ_API = `${BASE_URL}/faq`; // Keeping for backward compatibility if needed, or remove? Plan didn't explicitly say remove, but new one is /faqs
export const FAQS_API = `${BASE_URL}/faqs`;
export const PRESS_API = `${BASE_URL}/press`;
export const PRESS_RELEASES_API = `${BASE_URL}/press-releases`;
export const PRIVACY_POLICY_API = `${BASE_URL}/privacy-policy`;
export const SEO_API = `${BASE_URL}/pages`;
export const PROMOS_API = `${BASE_URL}/travel-promotions`;
export const DESTINATIONS_API = `${BASE_URL}/route-recommendations`;
export const BRANDING_API = `${BASE_URL}/gen_configs`;
export const GET_TO_KNOW_API = `${BASE_URL}/pages/home/page-sections/get_to_know`;
export const GET_TO_KNOW_MISSION_API = `${BASE_URL}/pages/home/page-sections/get_to_know_mission`;
export const GET_TO_KNOW_VISION_API = `${BASE_URL}/pages/home/page-sections/get_to_know_vision`;
export const WHY_CHOOSE_REASONS_API = `${BASE_URL}/home/why_choose/section-cards`;
export const WHY_CHOOSE_SECTION_API = `${BASE_URL}/pages/home/page-sections/why_choose`;
export const ABOUT_US_SECTION_API = `${BASE_URL}/pages/about-us/page-sections`;
export const OUR_PARTNERS_API = `${BASE_URL}/partners`;
export const ABOUT_US_CORE_VALUES_API = `${BASE_URL}/about-us/core_values/section-cards`;


