import { IPassengerType } from "@/models";

export const PASSENGER_TYPES_FALLBACK: IPassengerType[] = [
  {
    id: 1,
    code: "ADULT",
    name: "Adult",
    description: "Standard adult passenger (18-59 years old)",
    age_max: 59,
    age_min: 18,
    requires_id: false,
    sort_order: 1,
    is_active: true,
  },
  {
    id: 2,
    code: "CHILD",
    name: "Child",
    description: "Children passenger (5-12 years old)",
    age_max: 18,
    age_min: 5,
    requires_id: false,
    sort_order: 1,
    is_active: true,
  },
  {
    id: 5,
    code: "DRIVER",
    name: "Driver",
    description: "Drives a vehicle",
    age_max: null,
    age_min: null,
    requires_id: true,
    sort_order: 1,
    is_active: true,
  },
  {
    id: 6,
    code: "HELPER",
    name: "Helper",
    description: "Ge atras ge!. Ops bawi sa demano.",
    age_max: null,
    age_min: null,
    requires_id: false,
    sort_order: 1,
    is_active: true,
  },
  {
    id: 7,
    code: "INFANT",
    name: "Infant",
    description: "Little Angel",
    age_max: 2,
    age_min: 0,
    requires_id: false,
    sort_order: 1,
    is_active: true,
  },
  {
    id: 3,
    code: "PWD",
    name: "PWD",
    description: "Person With Disability",
    age_max: null,
    age_min: null,
    requires_id: true,
    sort_order: 1,
    is_active: true,
  },
  {
    id: 14,
    code: "PWDCHILD",
    name: "PWD Child",
    description: "PWD minor",
    age_max: 18,
    age_min: 1,
    requires_id: true,
    sort_order: 1,
    is_active: true,
  },
  {
    id: 4,
    code: "SENIOR",
    name: "Senior",
    description: "60+ Years old",
    age_max: 999,
    age_min: 60,
    requires_id: true,
    sort_order: 1,
    is_active: true,
  },
];
